### ISSUE TITLE
Beta version honeybadger-js

### ISSUE THREAD

**Issue by reabiliti** [honeybadger-io/honeybadger-react#188]
Hi all, could somebody create version which would work with https://www.npmjs.com/package/honeybadger-js/v/2.3.0-beta.0. Because there was fixed console log problem in this issue https://github.com/honeybadger-io/honeybadger-js/issues/397 and it's gonna be great to test it in react app.

**Comment by joshuap** [comment]
@reabiliti here's a beta version! https://www.npmjs.com/package/@honeybadger-io/react/v/0.0.8-beta.0
