### ISSUE TITLE
Fix documentation site

### ISSUE THREAD

**Issue by alexpapworth** [honeybadger-io/honeybadger-react#253]
## What are the steps to reproduce this issue?
1. Set up honeybadger-react using code suggested for `main.js` on the [honeybadger.io documentation](https://docs.honeybadger.io/lib/javascript/integration/react.html) site
2. Observe "Unable to send error report: no API key has been configured" error in console

## What happens?
API key is not set up correctly.

## Any logs, error output, etc?
```
[Honeybadger] – "Unable to send error report: no API key has been configured"
```
<img width="1280" alt="Screenshot 2021-02-04 at 22 23 08" src="https://user-images.githubusercontent.com/25950768/106962956-c885b480-6737-11eb-8493-acbfc61a6943.png">

## Any other comments?
Obviously nothing to change in this repository, but figured it would be the easiest way to alert y'all to the issue. It essentially comes down to this:

The [documentation page](https://docs.honeybadger.io/lib/javascript/integration/react.html) suggests you set up `const config` with a key called `api_key`, but it should actually be set up with `apiKey`, as seen in this repositories [example](https://github.com/honeybadger-io/honeybadger-react/blob/216793ec33eaa40ce328163072a4fdecb89c2878/example/src/index.js#L11).

## What versions are you using?
**Operating System:** macOS
**Package Version:** 1.0.0
**Browser Version:** Safari 13.0.2

**Comment by rubendinho** [comment]
Just ran into this as well.

**Comment by joshuap** [comment]
Sorry about that, that doc has been updated. Thanks for the heads up!

**Comment by alexpapworth** [comment]
No worries. Thanks for resolving! 🥳
