### ISSUE TITLE
Bump peerDependencies version

### ISSUE THREAD

**Issue by bs85** [honeybadger-io/honeybadger-react#254]
Installing the package along react 17 warns:

`@honeybadger-io/react@1.0.0" has incorrect peer dependency "react@^15.0.0 || ^16.0.0"`

Could ^17 be added? Could setting the version to `*` be an option?

**Comment by joshuap** [comment]
@bs85 released in 1.0.1. I may try `*` in the future, but went with `^17` for now. Thanks for the heads up!
