### ISSUE TITLE
Missing sourcemaps or a misconfigured package with Create React App - CRA

### ISSUE THREAD

**Issue by ktalley** [honeybadger-io/honeybadger-react#293]
After updating to the newest version of Create React App I'm getting warnings for missing sourcemap files in this package. See below for the exact warnings, and [see this issue](https://github.com/facebook/create-react-app/discussions/11767) for similar warnings.

## What are the steps to reproduce this issue?
1. Update any project using CRA to v5 and include the Honeybadger React library.
1a. Here's an [example repo](https://github.com/ktalley/issue-honeybadger-cra) if you need one to test with
2. Start the dev server `npm run start` or build `npm run build`

## What happens?
```
WARNING in ./node_modules/@honeybadger-io/react/dist/honeybadger-react.esm.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '<project>/node_modules/@honeybadger-io/src/DefaultErrorComponent.tsx' file: Error: ENOENT: no such file or directory, open '<project>/node_modules/@honeybadger-io/src/DefaultErrorComponent.tsx'
```

## What were you expecting to happen?
No errors or warnings

## What versions are you using?
**Operating System:** MacOS 10.15.7 / Node 16.3.0
**Package Version:** 2.0.0
**Browser Version:** N/A

**Comment by joshuap** [comment]
@ktalley thanks! We'll take a look.

**Comment by subzero10** [comment]
Hey @joshuap , I'm currently looking at this and it seems that it's the same issue described [here](https://github.com/facebook/create-react-app/discussions/11767#discussioncomment-2299945).

Basically, we are generating source maps for files that we do not ship with the package. We only distribute the `dist` folder, but the source maps point to the source code which is in the `src` folder. I'm trying to understand the reason we generate these source maps, do you know why?

**Comment by joshuap** [comment]
> Hey @joshuap , I'm currently looking at this and it seems that it's the same issue described [here](https://github.com/facebook/create-react-app/discussions/11767#discussioncomment-2299945).
> 
> Basically, we are generating source maps for files that we do not ship with the package. We only distribute the `dist` folder, but the source maps point to the source code which is in the `src` folder. I'm trying to understand the reason we generate these source maps, do you know why?

I don't really have a reason besides that it seems useful to point back to the original source, even if it's not included in the NPM package. Occasionally honeybadger.js will appear in a stack trace, and having the source map is handy. I didn't realize the physical source files were required to be in the package? (This is the first I'm hearing of it if so.)

I'm OK with changing this if it's not conventional.

**Comment by subzero10** [comment]
> Occasionally honeybadger.js will appear in a stack trace, and having the source map is handy.

How does this work though if the source is not available? My guess is that the source map won't have any effect.

> I didn't realize the physical source files were required to be in the package?

I don't think they should be required. However we are generating source maps that point to them, which seems useless right?

**Comment by subzero10** [comment]
> Do you mean that source maps other than honeybadger.min.js.map and honeybadger.js.map are being generated?

These are the generated files:
<img width="329" alt="image" src="https://user-images.githubusercontent.com/5813382/158257652-491d00af-0f12-4b51-b765-4d4db83885cc.png">

> In Honeybadger we have the [ability to link the source files to GitHub](https://docs.honeybadger.io/lib/javascript/guides/using-source-maps/#improving-error-grouping-and-linking-to-source-code)—so they don't necessarily need to exist on disk.

True, but our users link **their** github repositories, so they still can't link to the source code of Honeybadger, right?

> But also, doesn't the sourcesContent property in the source map file contain the original source code?

No, it's `null`:
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/5813382/158257776-20be38ec-efd7-4c90-a76a-49713ad7c683.png">
But this could be another solution we can look into. [Here's](https://github.com/rollup/plugins/issues/260) the suggested way to fix that. I will give this a go and let you know.

**Comment by subzero10** [comment]
@joshuap Your pointer to `sourcesContent`, seems to have made the error go away and we can keep source maps generation. [PR](https://github.com/honeybadger-io/honeybadger-react/pull/299) for review.

**Comment by joshuap** [comment]
> Thank you both so much! 🙌 Will 2.0.1 be published to NPM soon?

Oops, I thought I had, but looks like the command had failed. It should be up now:

https://www.npmjs.com/package/@honeybadger-io/react/v/2.0.1
