### ISSUE TITLE
react@18 support

### ISSUE THREAD

**Issue by JustFly1984** [honeybadger-io/honeybadger-react#330]
While installing packages I see `warning " > @honeybadger-io/react@2.0.1" has incorrect peer dependency "react@^15.0.0 || ^16.0.0 || ^17.0.0".` in npm log

**Comment by subzero10** [comment]
Thank you @JustFly1984! I'm working on this already!

**Comment by subzero10** [comment]
@JustFly1984 this should be fixed with the latest release (v2.1.0).
