### ISSUE TITLE
TypeScript types are not included in npm package

### ISSUE THREAD

**Issue by schontz** [honeybadger-io/honeybadger-react#87]
## What are the steps to reproduce this issue?
1. `npm install @honeybadger-io/react`
2. `cd node_modules/@honeybadger-io/react/`
3. `cat package.json | grep "d.ts"` => `"types": "./honeybadger-react.d.ts",`. Types are listed, so I know I am using a version that knows about types in the package.
4. `ls honeybadger-react.d.ts` => nothing. types are not included.

## What happens?
The types are not delivered with the module.

## What were you expecting to happen?
Types!

## Any other comments?
`wget https://raw.githubusercontent.com/honeybadger-io/honeybadger-react/master/honeybadger-react.d.ts` solves the problem, so the file is simply being omitted from the module.

## What versions are you using?
**Operating System:** Mac OS X
**Package Version:** 0.0.5
**Browser Version:** N/A

**Comment by joshuap** [comment]
Thanks for the report, @schontz. I think the problem is that honeybadger-react.d.ts is omitted from the `files` property: https://github.com/honeybadger-io/honeybadger-react/blob/master/package.json#L61

I'll get this fixed.
